export const dom = {
  confirmProfileModal: document.getElementById('confirm-profile-modal'),
  confirmProfileBackdrop: document.getElementById('confirm-profile-backdrop'),
  confirmProfileCancel: document.getElementById('confirm-profile-cancel'),
  confirmProfileConfirm: document.getElementById('confirm-profile-confirm'),
  exportMemoryBtn: document.getElementById('export-memory-btn'),
  importMemoryBtn: document.getElementById('import-memory-btn'),
  importMemoryInput: document.getElementById('import-memory-input'),

  chatBox: document.getElementById('chat-box'),
  composerCenter: document.querySelector('.composer-center'),
  userInput: document.getElementById('user-input'),
  sendBtn: document.getElementById('send-btn'),
  virtualKeyboard: document.getElementById('virtual-keyboard'),
  composerActions: document.getElementById('composer-actions'),
  composerActionsBtn: document.getElementById('composer-actions-btn'),
  composerActionsMenu: document.getElementById('composer-actions-menu'),
  recordBtn: document.getElementById('record-btn'),
  imageBtn: document.getElementById('image-btn'),
  imageInput: document.getElementById('image-input'),
  cameraBtn: document.getElementById('camera-btn'),
  cameraInput: document.getElementById('camera-input'),

  imagePreviewContainer: document.getElementById('image-preview-container'),
  imagePreview: document.getElementById('image-preview'),
  faceCountBadge: document.getElementById('face-count-badge'),
  faceCrops: document.getElementById('face-crops'),

  waveform: document.getElementById('waveform'),
  recordingStatus: document.getElementById('recording-status'),
  recordingTime: document.getElementById('recording-time'),
  recordingUI: document.getElementById('recording-ui'),

  synapseTrigger: document.getElementById('synapse-trigger'),
  synapseModal: document.getElementById('synapse-modal'),
  synapseBackdrop: document.getElementById('synapse-backdrop'),
  synapseCloseBtn: document.getElementById('synapse-close-btn'),

  settingsTrigger: document.getElementById('lipu-settings-trigger'),
  settingsModal: document.getElementById('settings-modal'),
  settingsBackdrop: document.getElementById('settings-backdrop'),
  settingsCloseBtn: document.getElementById('settings-close-btn'),
  replyModeInputs: document.querySelectorAll('input[name="lipu-reply-mode"]'),
  userProfileInputs: document.querySelectorAll('input[name="lipu-user-profile"]'),
  particleThemePalette: document.getElementById('particle-theme-palette'),
  particleThemeSaveBtn: document.getElementById('particle-theme-save-btn'),
  particleThemeExportBtn: document.getElementById('particle-theme-export-btn'),
  particleThemeImportBtn: document.getElementById('particle-theme-import-btn'),
  particleThemeImportInput: document.getElementById('particle-theme-import-input'),

  enrollFaceNameInput: document.getElementById('enroll-face-name-input'),
  enrollFaceInput: document.getElementById('enroll-face-input'),
  enrollFaceGenerateBtn: document.getElementById('enroll-face-generate-btn'),
  enrollFaceDeleteBtn: document.getElementById('enroll-face-delete-btn'),
  enrollFaceExportBtn: document.getElementById('enroll-face-export-btn'),
  enrollFaceStatus: document.getElementById('enroll-face-status'),
  enrollFaceProgressWrap: document.getElementById('enroll-face-progress-wrap'),
  enrollFaceProgressBar: document.getElementById('enroll-face-progress-bar'),
  enrollFaceProgressText: document.getElementById('enroll-face-progress-text'),
  enrollFacePeopleList: document.getElementById('enroll-face-people-list'),
  enrollFacePreview: document.getElementById('enroll-face-preview'),
  enrollFaceCrops: document.getElementById('enroll-face-crops')
};
